### ISSUE TITLE
URL acceptatie-omgeving in panoviewer.min.js

### ISSUE THREAD

**Issue by jsoetendal** [Amsterdam/PanoViewer#9]
In het bestand https://panoviewer.data.amsterdam.nl/dist/panoviewer.min.js staat nog de url API_ROOT:"https://acc.api.data.amsterdam.nl/".
Pas als je daar de 'acc.' weghaalt werkt het ook voor buitenstaanders als een zonnetje :)

**Comment by aditudorache** [comment]
solved in the last version
